config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'chatroom#index'
  get 'login', to: 'sessions#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
def index

end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new

end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned medium icon header  ">
  <i class="circular users icon teal"></i>
  Say Something!!!!
</h2>


<div class="ui two column grid">
  <div class="twelve wide column ">
    <div class="ui fluid raised card chatbox">
      <div class="content">
<div class="ui small feed">
  <h4 class="ui header">Followers Activity</h4>
  <div class="event">
    <div class="content">
      <div class="summary">
        <a>Elliot Fu</a> added <a>Jenny Hess</a> as a friend
      </div>
    </div>
  </div>
  <div class="event">
    <div class="content">
      <div class="summary">
        <a>Stevie Feliciano</a> added <a>Elliot Fu</a> as a friend
      </div>
    </div>
  </div>
  <div class="event">
    <div class="content">
      <div class="summary">
        <a>Helen Troy</a> added <a>Christian Rocha</a> as a friend
      </div>
    </div>
  </div>
  <div class="event">
    <div class="content">
      <div class="summary">
        <em>Christian Rocha</em> : Test message.
      </div>
    </div>
  </div>
      </div>
        </div>
      <div class=" extra content">
      <form class="ui reply form">
        <div class="field">
        </div>
        <div class="ui  fluid icon input ">
          <input type="text" placeholder="Enter a Message...">
          <i class="bordered inverted teal edit icon"></i>
        </div>

      </form>
      </div>
</div>
  </div>


  <div class="four wide column ">
    <div class="ui fluid raised card chatbox">
      <div class="content">
<div class="ui inverted grey vertical menu">
  <a class="active item">
    Home
  </a>
  <a class="item">
    <div class="ui small teal label">10</div>
    Messages
  </a>
  <a class="item">
    <div class="ui small teal label">12</div>
    Online Friends
  </a>
</div>
  </div>
    </div>
    </div>
</div>

app/views/layouts/_navigation.html.erb
 <div class="ui grey inverted menu ">

      <%= link_to "ChatBox", root_path, class:"active item"%>

    <a class="item">
      Messages
    </a>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <a class="item">Log Out</a>
          <%= link_to "Log in",login_path, class:"item" %>
          <a class="item">Sign Up</a>
        </div>
      </div>
      <div class="item">
        <div class="ui teal button">Sign Up</div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageBox</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= render 'layouts/navigation'%>

  <div class="ui container">
    <%= yield %>
  </div>
  </body>
</html>